In [1]:
import numpy as np
from scipy.linalg import lu

N = 5
A = np.random.randint(1000, size=(N, N))
P, L, U = lu(A)

def dot_product(P, L, U):
    return np.dot(P, np.dot(L, U))

print(f"A:\n{A}\n\nP:\n{P}\n\nL:\n{L}\n\nU:\n{U}")
print(f"\nDot product:\n{dot_product(P, L, U)}")

A:
[[879 289 687 538 328]
 [ 72  10 562 426 829]
 [626 199 159  77 616]
 [981 894 479 983 250]
 [802 778 962 766 784]]

P:
[[0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]

L:
[[ 1.          0.          0.          0.          0.        ]
 [ 0.89602446  1.          0.          0.          0.        ]
 [ 0.81753313 -0.09203352  1.          0.          0.        ]
 [ 0.0733945   0.10861269  0.8396221   1.          0.        ]
 [ 0.63812436  0.72548809 -0.56165566 -0.75793109  1.        ]]

U:
[[ 981.          894.          479.          983.          250.        ]
 [   0.         -512.04587156  257.80428135 -342.79204893  103.99388379]
 [   0.            0.          594.12826562  -69.18342401  589.18764047]
 [   0.            0.            0.          449.17270872  304.66135834]
 [   0.            0.            0.            0.          942.85547682]]

Dot product:
[[879. 289. 687. 538. 328.]
 [ 72.  10. 562. 426. 829.]
 [626. 199. 159.  77. 616.