In [4]:
import numpy as np
from scipy.linalg import lu

N = 5
A = np.random.randint(1000, size=(N, N))
P, L, U = lu(A)

def dot_product(P, L, U):
    return np.dot(P, np.dot(L, U))

print(f"A matrix:\n{A}")
print(f"\nDot product of PLU:\n{dot_product(P, L, U)}")

A matrix:
[[253 567 890 797 524]
 [978 119 585 934 370]
 [696 746  96 977 903]
 [205 850 675  62 660]
 [716 220 176 985 314]]

Dot product of PLU:
[[253. 567. 890. 797. 524.]
 [978. 119. 585. 934. 370.]
 [696. 746.  96. 977. 903.]
 [205. 850. 675.  62. 660.]
 [716. 220. 176. 985. 314.]]
